name = "dumb-questions-counter-app"
compatibility_date = "2024-01-15"

[env.production]
name = "dumb-questions-counter-app"

# Assets configuration for Cloudflare Pages
[assets]
directory = "./dist"

# Build configuration for Cloudflare Pages
[build]
command = "npm run build:cloudflare"
cwd = "."
watch_dir = "src"
